name: AI Service CI
on:
  push:
    paths:
      - 'ai-service/**'
  pull_request:
    paths:
      - 'ai-service/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
        working-directory: ./ai-service
      - run: pytest
        working-directory: ./ai-service
